version: "3.6"
services:
  bootstrap_node:
    image: xgreenx99/go-xpx:0.3.1
    volumes:
      - ./bootstrap_node/.xpx:/root/.xpx:rw
    restart: always
    command: sh -c "dfms --port 9080"
    network_mode: "host"

  onboarded_node_1:
    image: xgreenx99/go-xpx:0.3.1
    volumes:
      - ./onboarded_node_1/.xpx:/root/.xpx:rw
    restart: always
    command: sh -c "dfms --port 10080"
    network_mode: "host"
    depends_on:
      - bootstrap_node

  onboarded_node_2:
    image: xgreenx99/go-xpx:0.3.1
    volumes:
      - ./onboarded_node_2/.xpx:/root/.xpx:rw
    restart: always
    command: sh -c "dfms --port 11080"
    network_mode: "host"
    depends_on:
      - bootstrap_node

  not_onboarded_node:
    image: xgreenx99/go-xpx:0.3.1
    volumes:
      - ./not_onboarded_node/.xpx:/root/.xpx:rw
    restart: always
    command: sh -c "dfms --port 12080"
    network_mode: "host"
    depends_on:
      - bootstrap_node

  empty_node:
    image: xgreenx99/go-xpx:0.3.1
    volumes:
      - ./empty_node/.xpx:/root/.xpx:rw
    restart: always
    command: sh -c 'while :; do sleep 10; done'
    network_mode: "host"
    depends_on:
      - bootstrap_node
