version: "3.6"
services:
  db:
    image: mongo
    command: bash -c "mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    ports:
      - 27017:27017
    volumes:
    - ./mongodata:/dbdata:rw

  init-db:
    image: mongo
    command:  bash -c "/bin/bash /userconfig/mongors.sh"
    volumes:
    - ./mongodata:/dbdata:rw
    - ./scripts/mongo:/userconfig/:ro
    depends_on:
    - db

  catapult-api-node:
    # Downloads Catapult Server from specified Docker repo
    image: xgreenx99/proximax-catapult-server:0.4.2
    ports:
      - 7902:7902
      - 7900:7900
      - 7901:7901
    volumes:
      - ./:/catapultconfig
      - ./data:/data:rw
    restart: always
    # command: sh -c "/catapult/bin/catapult.server /catapultconfig"

  rest-gateway:
    image: xgreenx99/proximax-catapult-rest:0.4.8
    ports:
    - "3000:3000"
    volumes:
    - ./restuserconfig:/userconfig/
    command: ash -c "npm start resources/rest.json /userconfig/rest.json"

  block-explorer:
    image: techbureau/catapult-block-explorer
    command: ["python", "-m", "http.server", "8000"]
    ports:
    - "8000:8000"
